services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/dictrack:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb
      - PYTHONPATH=/workspaces/dictrack/app
    links:
      - redis
      - mongodb
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:6.2
    # ports:
    #   - "6379:6379"

  mongodb:
    image: mongo:5.0
    # ports:
    #   - "27017:27017"
